name: Deploy to Staging

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGE_SSH_KEY }}

      - name: Sync only html folder to staging server
        run: |
          echo "=== Starting rsync deployment ==="
          rsync -avz --delete --stats \
            --exclude='.git*' \
            --exclude='*.log' \
            --exclude='test_*.php' \
            --exclude='.env' \
            ./html/ pm2f7nn8yhci@staging.eduxoncabs.com:/home/pm2f7nn8yhci/stage_public_html/

          echo "=== Setting permissions on server ==="
          ssh -o StrictHostKeyChecking=no pm2f7nn8yhci@staging.eduxoncabs.com << 'EOF'
            # Keep .env safe
            chmod 600 /home/pm2f7nn8yhci/stage_public_html/.env 2>/dev/null || true

            # Normal permissions for the rest
            find /home/pm2f7nn8yhci/stage_public_html/ -type f ! -name ".env" -exec chmod 644 {} \;
            find /home/pm2f7nn8yhci/stage_public_html/ -type d -exec chmod 755 {} \;
          EOF

          echo "=== Deployment finished ==="
